import type { Category, Order, Product, Testimonial } from "./types";

export const categories: Category[] = [
  { id: "c1", name: "Go‘zallik", slug: "gozallik", emoji: "💄", productsCount: 184, gradient: "from-pink-500 to-rose-400" },
  { id: "c2", name: "Salomatlik", slug: "salomatlik", emoji: "🩺", productsCount: 142, gradient: "from-emerald-500 to-teal-400" },
  { id: "c3", name: "Uy-ro‘zg‘or", slug: "uy-rozgor", emoji: "🏠", productsCount: 263, gradient: "from-amber-500 to-orange-400" },
  { id: "c4", name: "Bolalar uchun", slug: "bolalar", emoji: "🧸", productsCount: 121, gradient: "from-sky-500 to-blue-400" },
  { id: "c5", name: "Avto aksessuar", slug: "avto", emoji: "🚗", productsCount: 98, gradient: "from-slate-600 to-slate-400" },
  { id: "c6", name: "Elektronika", slug: "elektronika", emoji: "📱", productsCount: 176, gradient: "from-indigo-600 to-violet-500" },
  { id: "c7", name: "Kitoblar", slug: "kitoblar", emoji: "📚", productsCount: 87, gradient: "from-orange-600 to-amber-500" },
  { id: "c8", name: "Trend mahsulotlar", slug: "trend", emoji: "🔥", productsCount: 204, gradient: "from-fuchsia-600 to-pink-500" },
  { id: "c9", name: "Sovg‘alar", slug: "sovgalar", emoji: "🎁", productsCount: 64, gradient: "from-violet-600 to-purple-500" },
  { id: "c10", name: "Kundalik", slug: "kundalik", emoji: "🛒", productsCount: 312, gradient: "from-cyan-600 to-sky-500" },
];

const baseSpecs = (extra: { label: string; value: string }[] = []) => [
  { label: "Brend", value: "200k Select" },
  { label: "Kafolat", value: "Operator orqali" },
  { label: "Yetkazib berish", value: "1–3 kun" },
  ...extra,
];

export const products: Product[] = [
  {
    id: "p1",
    title: "Bolalar uchun interaktiv o‘quv kompyuteri",
    slug: "interaktiv-oquv-kompyuteri",
    category: "bolalar",
    price: 149000,
    oldPrice: 199000,
    emoji: "🧮",
    gradient: "from-sky-500 to-blue-400",
    rating: 4.8,
    reviewsCount: 412,
    ordersCount: 5397,
    badges: ["Yangi"],
    description:
      "Bolangiz uchun harflar, raqamlar va musiqa bilan o‘rgatuvchi interaktiv o‘quv kompyuteri. Yorqin ekran, ko‘plab interaktiv o‘yinlar va xavfsiz materiallardan tayyorlangan.",
    specifications: baseSpecs([
      { label: "Yosh", value: "3–7 yosh" },
      { label: "Tillar", value: "O‘zbek, rus, ingliz" },
      { label: "Quvvat", value: "Batareya AA x3" },
    ]),
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "p2",
    title: "Damas pechka havo deflektori",
    slug: "damas-havo-deflektori",
    category: "avto",
    price: 159000,
    emoji: "🚙",
    gradient: "from-slate-600 to-slate-400",
    rating: 4.6,
    reviewsCount: 233,
    ordersCount: 5396,
    badges: ["Top"],
    description:
      "Damas avtomobili uchun havo deflektori. Salonni samarali isitadi va sovuq havoni to‘g‘ri taqsimlaydi. O‘rnatish oson.",
    specifications: baseSpecs([
      { label: "Material", value: "ABS plastik" },
      { label: "Moslik", value: "Damas / Labo" },
    ]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p3",
    title: "Teri muammolariga qarshi tabiiy malham",
    slug: "teri-malham",
    category: "salomatlik",
    price: 69000,
    oldPrice: 149000,
    emoji: "🧴",
    gradient: "from-emerald-500 to-teal-400",
    rating: 4.7,
    reviewsCount: 528,
    ordersCount: 5395,
    badges: ["Chegirma", "Hot"],
    description:
      "O‘simlik ekstraktlari asosidagi malham teri muammolarini yumshatishga yordam beradi. Kuniga 2 marta surtiladi.",
    specifications: baseSpecs([
      { label: "Hajm", value: "30 ml" },
      { label: "Tarkib", value: "Tabiiy ekstraktlar" },
    ]),
    inStock: true,
    isNew: true,
  },
  {
    id: "p4",
    title: "Oyoqlar uchun o‘simlik asosidagi sprey",
    slug: "oyoq-sprey",
    category: "salomatlik",
    price: 79000,
    oldPrice: 140000,
    emoji: "🦶",
    gradient: "from-green-500 to-emerald-400",
    rating: 4.5,
    reviewsCount: 198,
    ordersCount: 5394,
    badges: ["Chegirma"],
    description:
      "Oyoqlarni tetiklashtiruvchi va yoqimsiz hidga qarshi o‘simlik asosidagi sprey. Kunlik foydalanish uchun mos.",
    specifications: baseSpecs([{ label: "Hajm", value: "100 ml" }]),
    inStock: true,
    isNew: true,
  },
  {
    id: "p5",
    title: "Chivin to‘ri oyna uchun 150x150 sm",
    slug: "chivin-tori-150",
    category: "uy-rozgor",
    price: 69000,
    oldPrice: 99000,
    emoji: "🪟",
    gradient: "from-amber-500 to-orange-400",
    rating: 4.4,
    reviewsCount: 144,
    ordersCount: 5391,
    badges: ["Chegirma"],
    description:
      "Oynaga oson o‘rnatiladigan chivin to‘ri. Yopishqoq lenta bilan birga keladi, kesib o‘lchamga moslash mumkin.",
    specifications: baseSpecs([
      { label: "O‘lcham", value: "150 x 150 sm" },
      { label: "Rang", value: "Oq / Qora" },
    ]),
    inStock: true,
    isNew: true,
  },
  {
    id: "p6",
    title: "Muqaddima — Ibn Xaldun to‘plami",
    slug: "muqaddima-ibn-xaldun",
    category: "kitoblar",
    price: 289000,
    oldPrice: 399000,
    emoji: "📖",
    gradient: "from-orange-600 to-amber-500",
    rating: 5.0,
    reviewsCount: 176,
    ordersCount: 5388,
    badges: ["Chegirma", "Top"],
    description:
      "Ibn Xaldunning mashhur «Muqaddima» asari to‘plami. Sifatli qattiq muqovada, zamonaviy tarjimada.",
    specifications: baseSpecs([
      { label: "Muqova", value: "Qattiq" },
      { label: "Til", value: "O‘zbek" },
    ]),
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "p7",
    title: "Islom psixologiyasi kitobi",
    slug: "islom-psixologiyasi",
    category: "kitoblar",
    price: 119000,
    oldPrice: 199000,
    emoji: "📗",
    gradient: "from-teal-600 to-emerald-500",
    rating: 4.9,
    reviewsCount: 211,
    ordersCount: 5387,
    badges: ["Chegirma"],
    description:
      "Inson ruhiyati va o‘zini anglash haqida chuqur mulohazalarni o‘z ichiga olgan kitob.",
    specifications: baseSpecs([{ label: "Til", value: "O‘zbek" }]),
    inStock: true,
    isNew: true,
  },
  {
    id: "p8",
    title: "Ovozli antistress yumshoq o‘yinchoq",
    slug: "antistress-oyinchoq",
    category: "bolalar",
    price: 59000,
    emoji: "🧸",
    gradient: "from-fuchsia-500 to-pink-400",
    rating: 4.6,
    reviewsCount: 167,
    ordersCount: 5386,
    badges: ["Yangi", "Bugun trendda"],
    description:
      "Stressni kamaytiruvchi yumshoq antistress o‘yinchoq. Bolalar va kattalar uchun mos, ovozli effektlar bilan.",
    specifications: baseSpecs([{ label: "Material", value: "Yumshoq silikon" }]),
    inStock: true,
    isNew: true,
  },
  {
    id: "p9",
    title: "Qoshlar uchun fiksator gel",
    slug: "qosh-fiksator-gel",
    category: "gozallik",
    price: 97000,
    oldPrice: 126000,
    emoji: "✨",
    gradient: "from-pink-500 to-rose-400",
    rating: 4.7,
    reviewsCount: 389,
    ordersCount: 2563,
    badges: ["Ko‘p sotilgan"],
    description:
      "Qoshlarni kun bo‘yi tabiiy holatda ushlab turuvchi shaffof fiksator gel. Yopishqoq emas, tabiiy ko‘rinish beradi.",
    specifications: baseSpecs([{ label: "Hajm", value: "8 ml" }]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p10",
    title: "Iyak ko‘tarish uchun bandaj",
    slug: "iyak-bandaj",
    category: "salomatlik",
    price: 127000,
    oldPrice: 165000,
    emoji: "💆",
    gradient: "from-emerald-500 to-green-400",
    rating: 4.5,
    reviewsCount: 254,
    ordersCount: 2710,
    badges: ["Ko‘p sotilgan", "Hot"],
    description:
      "Yuz va iyak konturini tortib turuvchi qulay bandaj. Elastik material, terini bezovta qilmaydi.",
    specifications: baseSpecs([{ label: "O‘lcham", value: "Universal" }]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p11",
    title: "Elektr tirnoq kesgich",
    slug: "elektr-tirnoq-kesgich",
    category: "gozallik",
    price: 77000,
    oldPrice: 100000,
    emoji: "💅",
    gradient: "from-rose-500 to-pink-400",
    rating: 4.6,
    reviewsCount: 312,
    ordersCount: 2649,
    badges: ["Ko‘p sotilgan"],
    description:
      "Xavfsiz va qulay elektr tirnoq kesgich. Bolalar va kattalar uchun mos, USB orqali quvvatlanadi.",
    specifications: baseSpecs([{ label: "Quvvat", value: "USB akkumulyator" }]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p12",
    title: "Oltin tarkibli yuz niqobi",
    slug: "oltin-yuz-niqobi",
    category: "gozallik",
    price: 49000,
    oldPrice: 64000,
    emoji: "🌟",
    gradient: "from-amber-500 to-yellow-400",
    rating: 4.4,
    reviewsCount: 276,
    ordersCount: 2624,
    badges: ["Ko‘p sotilgan"],
    description:
      "Terini namlantiradigan va tetiklashtiradigan oltin tarkibli niqob. Haftada 2–3 marta qo‘llaniladi.",
    specifications: baseSpecs([{ label: "Hajm", value: "120 g" }]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p13",
    title: "Quruq shampun (yuvishsiz)",
    slug: "quruq-shampun",
    category: "gozallik",
    price: 59000,
    oldPrice: 103000,
    emoji: "🧴",
    gradient: "from-violet-500 to-purple-400",
    rating: 4.5,
    reviewsCount: 341,
    ordersCount: 2602,
    badges: ["Ko‘p sotilgan", "Chegirma"],
    description:
      "Suvsiz sochlarni tozalaydigan quruq shampun. Sochga hajm beradi va yangi ko‘rinish bag‘ishlaydi.",
    specifications: baseSpecs([{ label: "Hajm", value: "150 ml" }]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p14",
    title: "Lablar uchun namlantiruvchi bo‘yoq",
    slug: "lab-boyoq",
    category: "gozallik",
    price: 49000,
    oldPrice: 64000,
    emoji: "💋",
    gradient: "from-rose-600 to-pink-500",
    rating: 4.6,
    reviewsCount: 298,
    ordersCount: 2461,
    badges: ["Ko‘p sotilgan"],
    description:
      "Lablarni namlantiradigan va tabiiy rang beradigan bo‘yoq. Kun bo‘yi qulay his.",
    specifications: baseSpecs([{ label: "Ranglar", value: "6 xil" }]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p15",
    title: "Oqartiruvchi tabiiy sovun",
    slug: "oqartiruvchi-sovun",
    category: "gozallik",
    price: 9000,
    oldPrice: 19000,
    emoji: "🧼",
    gradient: "from-cyan-500 to-sky-400",
    rating: 4.3,
    reviewsCount: 421,
    ordersCount: 2430,
    badges: ["Ko‘p sotilgan", "Hot"],
    description:
      "Terini tozalaydigan va yumshatadigan tabiiy sovun. Har kuni foydalanish mumkin.",
    specifications: baseSpecs([{ label: "Og‘irlik", value: "100 g" }]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p16",
    title: "Yuz uchun matlashtiruvchi primer",
    slug: "matlashtiruvchi-primer",
    category: "gozallik",
    price: 69000,
    oldPrice: 90000,
    emoji: "🎨",
    gradient: "from-fuchsia-500 to-violet-400",
    rating: 4.5,
    reviewsCount: 187,
    ordersCount: 2440,
    badges: ["Ko‘p sotilgan"],
    description:
      "Bo‘yanishdan oldin teriga silliqlik beradigan primer. Yog‘lanishni nazorat qiladi.",
    specifications: baseSpecs([{ label: "Hajm", value: "30 ml" }]),
    inStock: true,
    isPopular: true,
  },
  {
    id: "p17",
    title: "Aqlli LED tungi chiroq",
    slug: "led-tungi-chiroq",
    category: "uy-rozgor",
    price: 89000,
    oldPrice: 139000,
    emoji: "💡",
    gradient: "from-indigo-500 to-blue-400",
    rating: 4.7,
    reviewsCount: 203,
    ordersCount: 1980,
    badges: ["Yangi", "Bugun trendda"],
    description:
      "Harakatni sezadigan, rangini o‘zgartiradigan aqlli LED tungi chiroq. Yotoqxona uchun ideal.",
    specifications: baseSpecs([{ label: "Quvvat", value: "USB" }]),
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "p18",
    title: "Simsiz quloqchin TWS Pro",
    slug: "tws-pro-quloqchin",
    category: "elektronika",
    price: 199000,
    oldPrice: 320000,
    emoji: "🎧",
    gradient: "from-indigo-600 to-violet-500",
    rating: 4.8,
    reviewsCount: 512,
    ordersCount: 3120,
    badges: ["Hot", "Bugun trendda"],
    description:
      "Tiniq ovoz va kuchli bass beradigan simsiz quloqchin. Shovqinni kamaytirish va uzoq batareya quvvati.",
    specifications: baseSpecs([
      { label: "Ulanish", value: "Bluetooth 5.3" },
      { label: "Batareya", value: "5 soat + keys" },
    ]),
    inStock: true,
    isFeatured: true,
    isPopular: true,
  },
];

export const testimonials: Testimonial[] = [
  { name: "Aziza", city: "Toshkent", rating: 5, text: "Buyurtmam tez yetib keldi. Operator juda yaxshi tushuntirdi. Mahsulot sifati ham yaxshi." },
  { name: "Jasur", city: "Samarqand", rating: 5, text: "Click orqali to‘lov qildim, hammasi oson bo‘ldi. Yetkazib berish ham tez." },
  { name: "Madina", city: "Farg‘ona", rating: 5, text: "Mahsulot rasmda ko‘rsatilgandek keldi. Yana buyurtma qilaman." },
  { name: "Dilshod", city: "Andijon", rating: 5, text: "Narxlar qulay, mahsulotlar ko‘p. Sayt ishlatishga juda oson." },
  { name: "Sevara", city: "Buxoro", rating: 5, text: "Tez buyurtma qoldirdim, 10 daqiqada operator qo‘ng‘iroq qildi. Zo‘r xizmat!" },
  { name: "Bekzod", city: "Namangan", rating: 5, text: "Naqd to‘lov bilan oldim, mahsulot sifatli chiqdi. Rahmat 200k.uz!" },
];

export const sampleOrders: Order[] = [
  {
    id: "200K-10428",
    date: "2026-06-08",
    status: "Yetkazilmoqda",
    total: 357000,
    itemsCount: 3,
    items: [
      { title: "Simsiz quloqchin TWS Pro", emoji: "🎧", gradient: "from-indigo-600 to-violet-500" },
      { title: "Quruq shampun", emoji: "🧴", gradient: "from-violet-500 to-purple-400" },
    ],
  },
  {
    id: "200K-10391",
    date: "2026-06-05",
    status: "Yetkazildi",
    total: 149000,
    itemsCount: 1,
    items: [
      { title: "Interaktiv o‘quv kompyuteri", emoji: "🧮", gradient: "from-sky-500 to-blue-400" },
    ],
  },
  {
    id: "200K-10355",
    date: "2026-06-01",
    status: "Operator bog‘landi",
    total: 206000,
    itemsCount: 2,
    items: [
      { title: "Oltin yuz niqobi", emoji: "🌟", gradient: "from-amber-500 to-yellow-400" },
      { title: "Elektr tirnoq kesgich", emoji: "💅", gradient: "from-rose-500 to-pink-400" },
    ],
  },
];

// Helpers
export const formatPrice = (n: number) =>
  new Intl.NumberFormat("ru-RU").format(n) + " so‘m";

export const discountPercent = (p: Product) =>
  p.oldPrice ? Math.round(((p.oldPrice - p.price) / p.oldPrice) * 100) : 0;

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);

export const getCategoryBySlug = (slug: string) =>
  categories.find((c) => c.slug === slug);

export const newProducts = products.filter((p) => p.isNew);
export const popularProducts = products.filter((p) => p.isPopular);
export const featuredProducts = products.filter((p) => p.isFeatured);
